blueprint:
  name: "Extracteur SDB - Humidité vs Référence + Min ON + Minuterie manuelle"
  description: >
    "Contrôle un extracteur (switch) selon l'écart d'humidité entre 2 capteurs (zone vs référence).
    Auto: ON si delta >= seuil ON, OFF si delta <= seuil OFF après un minimum ON.
    Manuel: si tu allumes le switch, il reste ON X minutes puis OFF."
  domain: automation

  input:
    fan_switch:
      name: "Commutateur du ventilateur"
      description: "Switch contrôlant le ventilateur. Exemple: switch.salle_de_bain"
      selector:
        entity:
          domain: switch

    humidity_sensor_zone:
      name: "Capteur humidité (zone ventilée)"
      description: "Humidité dans la pièce (ex: salle de lavage / salle de bain)"
      selector:
        entity:
          domain: sensor

    humidity_sensor_ref:
      name: "Capteur humidité (référence)"
      description: "Humidité de référence (ex: sous-sol)"
      selector:
        entity:
          domain: sensor

    delta_on:
      name: "Seuil ON (delta %)"
      description: "Allume si (zone - référence) >= ce seuil"
      default: 10
      selector:
        number:
          min: 0
          max: 50
          step: 0.5
          mode: slider
          unit_of_measurement: "%"

    delta_off:
      name: "Seuil OFF (delta %)"
      description: "Éteint si (zone - référence) <= ce seuil (doit être plus bas que ON)"
      default: 5
      selector:
        number:
          min: 0
          max: 50
          step: 0.5
          mode: slider
          unit_of_measurement: "%"

    min_on_minutes:
      name: "Minimum ON en mode auto (minutes)"
      description: "Une fois parti en auto, il reste ON au moins X minutes"
      default: 5
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider
          unit_of_measurement: "min"

    manual_minutes:
      name: "Durée ON si allumé manuellement (minutes)"
      description: "Quand tu allumes le switch, il reste ON X minutes puis s'éteint"
      default: 30
      selector:
        number:
          min: 1
          max: 180
          step: 1
          mode: slider
          unit_of_measurement: "min"

    poll_minutes:
      name: "Vérification périodique (minutes)"
      description: "Filet de sécurité (utile si les capteurs bougent peu)"
      default: 2
      selector:
        number:
          min: 1
          max: 10
          step: 1
          mode: slider
          unit_of_measurement: "min"

mode: restart

trigger:
  - platform: state
    entity_id: !input humidity_sensor_zone
  - platform: state
    entity_id: !input humidity_sensor_ref

  # Détecter l'allumage manuel (switch passe à on)
  - platform: state
    entity_id: !input fan_switch
    to: "on"

  - platform: time_pattern
    minutes: "/1"

variables:
  fan: !input fan_switch
  z: !input humidity_sensor_zone
  r: !input humidity_sensor_ref

  on_th: !input delta_on
  off_th: !input delta_off
  min_on: !input min_on_minutes
  manual_on: !input manual_minutes
  poll: !input poll_minutes

  hz: "{{ states(z) | float(none) }}"
  hr: "{{ states(r) | float(none) }}"
  delta: >-
    {% if hz is none or hr is none %}
      {{ none }}
    {% else %}
      {{ (hz - hr) | round(1) }}
    {% endif %}

  fan_is_on: "{{ is_state(fan, 'on') }}"

  # Temps ON actuel (secondes) selon last_changed du switch
  fan_on_seconds: >-
    {% if fan_is_on %}
      {{ (as_timestamp(now()) - as_timestamp(states[fan].last_changed)) | int }}
    {% else %}
      0
    {% endif %}

  # Filtre du trigger time_pattern: seulement aux X minutes (poll_minutes)
  time_tick_ok: >-
    {% if trigger.platform != 'time_pattern' %}
      true
    {% else %}
      {{ (now().minute % (poll | int)) == 0 }}
    {% endif %}

  # Détecter si ce run est causé par un allumage du switch (probablement manuel)
  triggered_by_switch_on: >-
    {{ trigger.platform == 'state'
       and trigger.entity_id == fan
       and trigger.to_state is not none
       and trigger.to_state.state == 'on' }}

condition:
  - condition: template
    value_template: "{{ time_tick_ok }}"

action:
  - choose:
      # ====== MODE MANUEL ======
      # Si le trigger est l'allumage du switch, on part un timer manuel.
      # NB: Si l'auto l'allume suite à humidité, ça va aussi déclencher ici.
      # Pour éviter ça, on ajoute une condition: delta doit être NONE ou en dessous du seuil ON,
      # sinon on considère que c'est auto (car l'humidité demande de ventiler).
      - conditions:
          - condition: template
            value_template: "{{ triggered_by_switch_on }}"
          - condition: template
            value_template: "{{ delta is none or (delta | float) < (on_th | float) }}"
        sequence:
          - delay:
              minutes: "{{ manual_on | int }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input fan_switch
                    state: "on"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: "{{ fan }}"

      # ====== AUTO ON ======
      - conditions:
          - condition: template
            value_template: "{{ delta is not none and (delta | float) >= (on_th | float) and not fan_is_on }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ fan }}"

      # ====== AUTO OFF ======
      - conditions:
          - condition: template
            value_template: >-
              {{ delta is not none
                 and (delta | float) <= (off_th | float)
                 and fan_is_on
                 and fan_on_seconds >= ((min_on | int) * 60) }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ fan }}"

    default: []
