blueprint:
  name: Humidity Management based on relative humidity (%)
  description: Turn a fan on and off based on the difference between a humidity sensor and a baseline, based on relative humidity.
  domain: automation
  input:
    humidity_sensor:
      name: Humidity Sensor
      description: A sensor that measures the relative humidity of the area to be vented, for example the shower.
      selector:
        entity:
          domain: sensor
    reference_humidity_sensor:
      name: Reference Humidity Sensor
      description: A sensor that indicates the baseline relative humidity of the area outside of the vented, for example the walkway outside the shower.
      selector:
        entity:
          domain: sensor
    fan_switch:
      name: Fan Switch (Dummy)
      description: A dummy switch that simulates the fan turning on and off.
      selector:
        entity:
          domain: input_boolean
    rising_threshold:
      name: Rising Threshold (%)
      description: The increase in relative humidity above the reference humidity that must occur before the fan is turned on.
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
      default: 10  # Adjust this to the percentage point increase needed to turn on the fan
    falling_threshold:
      name: Falling Threshold (%)
      description: The decrease in relative humidity below the reference humidity that must occur before the fan is turned off.
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
      default: 5   # Adjust this to the percentage point decrease needed to turn off the fan

trigger:
  - platform: state
    entity_id: !input "humidity_sensor"
  - platform: state
    entity_id: !input "reference_humidity_sensor"

condition:
  - condition: template
    value_template: "{{ mode != switch_state }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'on' }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input "fan_switch"
      - conditions:
          - condition: template
            value_template: "{{ mode == 'off' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input "fan_switch"

variables:
  humidity_sensor: !input "humidity_sensor"
  reference_humidity_sensor: !input "reference_humidity_sensor"
  fan_switch: !input "fan_switch"
  switch_state: "{{ states(fan_switch) }}"
  rising_threshold: !input "rising_threshold"
  falling_threshold: !input "falling_threshold"
  humid_percent: "{{ states(humidity_sensor) | float }}"
  ref_humid_percent: "{{ states(reference_humidity_sensor) | float }}"
  difference: "{{ humid_percent - ref_humid_percent }}"
  mode: "{% if switch_state == 'off' and difference > rising_threshold %}on{% elif switch_state == 'on' and difference < falling_threshold %}off{% else %}{{ switch_state }}{% endif %}"
mode: single
